package com.md.mdcms.xml;

public interface Xml {

	String CONTAINER = "CONTAINER";
	String CONTAINERTYPE = "TYPE";
	String CONTAINERID = "ID";
	String CONTAINERCAPTION = "CAPTION";
	String CONTAINERCAPTIONVALUE = "VALUE";
	String CONTAINERGRID = "GRID";
	String CONTAINERGRIDID = "ID";
	String CONTAINERGRIDMAXINDEX = "MAXINDEX";
	String CONTAINERFIELD = "FIELD";
	String CONTAINERFIELDBROWSE = "BROWSE";
	String CONTAINERFIELDEDITABLE = "EDITABLE";
	String CONTAINERFIELDLABEL = "LABEL";
	String CONTAINERFIELDID = "ID";
	String CONTAINERFIELDVALUE = "VALUE";
	String CONTAINERFIELDVISIBLE = "VISIBLE";
	String CONTAINERFIELDLIST = "LIST";
	String CONTAINERHEADER = "HEADER";
	String CONTAINERITEM = "ITEM";
	String CONTAINERITEMID = "ID";
	String CONTAINERITEMTYPE = "TYPE";
	String CONTAINERITEMFOCUS = "FOCUS";
	String CONTAINERITEMBROWSE = "BROWSE";
	String CONTAINERITEMSTATUS = "STATUS";
	String CONTAINERITEMLINK = "LINK";
	String CONTAINERITEMVALUE = "VALUE";
	String CONTAINERITEMEDITABLE = "EDITABLE";
	String CONTAINERITEMSEVERITY = "SEVERITY";
	String CONTAINERITEMVISIBLE = "VISIBLE";
	String CONTAINERITEMLIST = "LIST";
	String CONTAINERITEMLINKLIST = "LINKLIST";
	String CONTAINERTABLIST = "TABLIST";
	String CONTAINERTAB = "TAB";
	String CONTAINERTABID = "ID";
	String CONTAINERTABVALUE = "VALUE";
	String CONTAINERTABACTIVE = "ACTIVE";
	String CONTAINERARRAY = "ARRAY";
	String CONTAINERROW = "ROW";
	String CONTAINERROWS = "ROWS";
	String CONTAINERMESSAGELIST = "MESSAGELIST";
	String CONTAINERMESSAGELISTFIELDID = "FIELDID";
	String CONTAINERTYPEDROPDOWNLIST = "DROPDOWNLIST";
	String CONTAINERTABLE = "TABLE";
	String CONTAINERBOX = "BOX";

	String CONTAINERTYPEGLOBAL = "GLOBAL";
	String CONTAINERTYPESCREEN = "SCREEN";
	String CONTAINERTYPEREQUESTCODELIST = "REQUESTCODELIST";
	String CONTAINERTYPEKEYLIST = "KEYLIST";
	String CONTAINERTYPEBUTTON = "BUTTON";
	String CONTAINERTYPEMENU = "MENU";
	String CONTAINERTYPEHELP = "HELP";
	String CONTAINERTYPEPENDENZEN = "PENDENZEN";

	String FUNCTION_THREADEND = "*THREADEND";
	String SCREEN_LOGOFF = "*LOGOFF";

	String REQUESTCODETYPEBUTTON = "button";

}
